# Generated by Django 6.1 on 2026-08-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cart_order_orderitem_wishlist_cartitem_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_product_source_id'),
        ),
    ]
